### ISSUE TITLE
Error while attempting to update defold (ubuntu snap version)

### ISSUE THREAD

**Issue by EP2003a** [popey/defold-snap#1]
Log:

```
INFO:TOOLS: Launcher version e4aaff11f49c941fde1dd93883cf69c6b8abebe4
DEBUG:TOOLS: arg 0: /snap/defold/current/packages/jdk-17.0.5+8/bin/java
DEBUG:TOOLS: arg 1: -cp
DEBUG:TOOLS: arg 2: /snap/defold/current/packages/defold-4bed75905b7e1ddc3d30907ad2c6e8fbce3741e3.jar
DEBUG:TOOLS: arg 3: -Duser.home=/home/evan/snap/defold/current
DEBUG:TOOLS: arg 4: -Dfile.encoding=UTF-8
DEBUG:TOOLS: arg 5: -Djna.nosys=true
DEBUG:TOOLS: arg 6: -Ddefold.launcherpath=./Defold
DEBUG:TOOLS: arg 7: -Ddefold.resourcespath=/snap/defold/current
DEBUG:TOOLS: arg 8: -Ddefold.version=1.9.3
DEBUG:TOOLS: arg 9: -Ddefold.editor.sha1=4bed75905b7e1ddc3d30907ad2c6e8fbce3741e3
DEBUG:TOOLS: arg 10: -Ddefold.engine.sha1=e4aaff11f49c941fde1dd93883cf69c6b8abebe4
DEBUG:TOOLS: arg 11: -Ddefold.buildtime=2024-09-16T09:10:02.830989
DEBUG:TOOLS: arg 12: -Ddefold.channel=editor-alpha
DEBUG:TOOLS: arg 13: -Ddefold.archive.domain=d.defold.com
DEBUG:TOOLS: arg 14: -Djava.net.preferIPv4Stack=true
DEBUG:TOOLS: arg 15: -Dsun.net.client.defaultConnectTimeout=30000
DEBUG:TOOLS: arg 16: -Dsun.net.client.defaultReadTimeout=30000
DEBUG:TOOLS: arg 17: -Djogl.texture.notexrect=true
DEBUG:TOOLS: arg 18: -Dglass.accessible.force=false
DEBUG:TOOLS: arg 19: --add-opens=java.base/java.lang=ALL-UNNAMED
DEBUG:TOOLS: arg 20: --add-opens=java.desktop/sun.awt=ALL-UNNAMED
DEBUG:TOOLS: arg 21: --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED
DEBUG:TOOLS: arg 22: --add-opens=java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED
DEBUG:TOOLS: arg 23: --add-opens=java.base/sun.nio.fs=ALL-UNNAMED
DEBUG:TOOLS: arg 24: --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED
DEBUG:TOOLS: arg 25: -Xmx12460720128
DEBUG:TOOLS: arg 26: com.defold.editor.Main
DEBUG:TOOLS: arg 27: (null)
Picked up JAVA_TOOL_OPTIONS: 
Picked up _JAVA_OPTIONS: 
2024-11-21 21:14:12.677 WARN  default    javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @14b8849e'
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen

(java:69037): Gdk-WARNING **: 21:14:13.518: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2024-11-21 21:14:13.818 INFO  default    com.defold.libs.ResourceUnpacker - deleting old unpack dirs from /home/evan/snap/defold/current/.Defold/unpack
2024-11-21 21:14:13.823 INFO  default    com.defold.libs.ResourceUnpacker - Already unpacked for the editor version 4bed75905b7e1ddc3d30907ad2c6e8fbce3741e3
2024-11-21 21:14:13.826 INFO  default    com.defold.libs.ResourceUnpacker - defold.unpack.path=/home/evan/snap/defold/current/.Defold/unpack/4bed75905b7e1ddc3d30907ad2c6e8fbce3741e3
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen

(java:69037): Gdk-WARNING **: 21:14:16.638: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2024-11-21 21:14:17.262 INFO  default    editor.updater - {:line 303, :message "Checking for updates", :url "https://d.defold.com/editor2/channels/editor-alpha/update-v4.json"}
2024-11-21 21:14:18.090 INFO  default    editor.updater - {:line 310, :message "No update found"}
2024-11-21 21:14:23.442 INFO  default    editor.updater - {:line 264, :message "Installing update"}
2024-11-21 21:14:23.469 INFO  default    editor.ui.updater - {:line 38, :message "Update failed"}
java.nio.file.FileSystemException: /snap/defold/23/logo_blue.png: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:467)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at editor.updater$move_file_BANG_.invokeStatic(updater.clj:222)
	at editor.updater$install_unix_file_BANG_.invokeStatic(updater.clj:228)
	at editor.updater$install_file_BANG_.invokeStatic(updater.clj:244)
	at editor.updater$install_BANG_.invokeStatic(updater.clj:269)
	at editor.ui.updater$install_BANG_.invokeStatic(updater.clj:33)
	at editor.ui.updater$init_BANG_$fn__104292.invoke(updater.clj:51)
	at editor.ui$fn__15540$fn__15541.invoke(ui.clj:2085)
	at editor.ui$chain_handler$reify__15504.handle(ui.clj:2071)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:100)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:178)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:176)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1259)
	at com.sun.glass.ui.Window.notifyClose(Window.java:1164)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I believe this may be related to the error I get when trying to update defold, where, when I attempt to restart so as to download the update, it tells me there was an error.

**Comment by popey** [comment]
Apologies for the delay responding. I believe this is resolved, but anyone else seeing errors, please file a new issue. Thanks.
